### ISSUE TITLE
Parse error for ZipInputStream

### ISSUE THREAD

**Issue by skytiger0419** [3breadt/dd-plist#4] opened 2015-07-08 05:58 UTC
For FileInputstream is OK
For zFile.getInputStream(entry), Sometimes normal and sometimes is not normal 
input=zFile.getInputStream(entry)
PropertyListParser.parser(input)
error:
![qq 20150708135558](https://cloud.githubusercontent.com/assets/6157372/8564056/6d0e205c-2579-11e5-9bec-37b45834abcd.png)
for reason:
![debug](https://cloud.githubusercontent.com/assets/6157372/8564097/382d069a-257a-11e5-904f-664ed336fae7.png)

   /**
     * Reads all bytes from an InputStream and stores them in an array, up to
     * a maximum count.
     *
     * @param in  The InputStream pointing to the data that should be stored in the array.
     * @return An array containing all bytes that were read from the input stream.
     * @throws java.io.IOException When an IO error while reading from the input stream.
     */
    protected static byte[] readAll(InputStream in) throws IOException {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        byte[] buf = new byte[512];
        int read = 512;
        while (read == 512) {
            read = in.read(buf);
            if(read != -1)
                outputStream.write(buf, 0, read);
        }
        return outputStream.toByteArray();
    }
Will the above code truncate the input stream ? then Information is not complete.
This problem corresponding to the app : http://os-ios.liqucn.com/rj/22709.shtml

**Comment by 3breadt** [comment] 2015-07-08 21:04
It appears you are using an outdated version of the library. The readAll method had a bug regarding ZIP streams and regarding files whose size is a multiple of 512. Please try the latest release and see if the issue is still valid.

**Comment by 3breadt** [comment] 2015-07-20 06:33
Probably duplicate of #2. Close as duplicate.

**Closed by 3breadt** 2015-07-20 06:33 UTC
Labels: duplicate
