### ISSUE TITLE
OutOfMemoryError parsing a small plist file

### ISSUE THREAD

**Issue by lfcnassif** [3breadt/dd-plist#72] opened 2022-10-26 18:00 UTC
The attached 1.68KB plist file causes a 4GB int[] array allocation when parsed using dd-plist-1.23. It is possibly corrupted, but I think the library should defend itself against this to avoid DOS attacks. This was first reported at https://github.com/sepinf-inc/IPED/issues/1403

Let me know if you need some other information.

Thanks in advance.
[1061134322640399597.zip](https://github.com/3breadt/dd-plist/files/9872455/1061134322640399597.zip)

**Comment by lfcnassif** [comment] 2022-10-26 19:00
Update: this also happens with dd-plist-1.25

**Comment by 3breadt** [comment] 2022-10-29 13:42
The property list seems to be corrupted indeed. But how the library handled that file was really not optimal. Unnecessary memory allocation when parsing binary property lists has been reduced and the issue is now fixed.

**Closed by 3breadt** 2022-10-29 13:42 UTC
Labels: bug

**Comment by lfcnassif** [comment] 2022-10-29 15:04
Thank you very much, this was very fast! I'll test the fix with another triggering file and report back.

**Comment by lfcnassif** [comment] 2022-11-01 20:11
Just tested version 1.26 with another triggering file, the fix worked fine.

Thank you very much!
